name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Run Renovate
        uses: renovatebot/github-action@v41.0.10
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
          repositories: "csuvardaniel/csuvardaniel.github.io"
